### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/napari-plugin-template#3]
- [ ] add task print message to stdout
- [ ] validators
- [ ] add task to install pre-commit
- [ ] add docs, outside of readme this time (or at least, more readable)
